import 'whatwg-fetch';
import './domrect-polyfill';
import './adblock.js';
import './sponsorblock.js';
import './ui.js';
import './speedUI.js';
import './theme.js';
import './modernUI.js';
import './infinite-hd.js';
import './remove-login-popup.js';
// import './load-comments.js';
